### ISSUE TITLE
Wox v1.4.1196 无法使用此插件

### ISSUE THREAD

**Issue by Robin7Ma** [Zeroto521/Flow.Launcher.Plugin.Timestamp#1]
将代码下载后放置在Wox的插件目录，Wox可以加载并可以在插件管理界面看到，但使用ts关键字时无任何效果。

另外能否提供.wox后缀的插件文件？ 谢谢。

PS： 看介绍功能很不错，希望继续完善，加油！

**Comment by Zeroto521** [comment]
> 将代码下载后放置在Wox的插件目录，Wox可以加载并可以在插件管理界面看到，但使用ts关键字时无任何效果。

请确定环境内已装相关[依赖](https://github.com/Zeroto521/Flow.Launcher.Plugin.Timestamp/blob/wox/requirements.txt).

 > 另外能否提供.wox后缀的插件文件？ 谢谢。

`.wox` 本质即为 `.zip` 文件, 请自行下载.

https://github.com/Zeroto521/Flow.Launcher.Plugin.Timestamp/archive/refs/heads/wox.zip

**Comment by Zeroto521** [comment]
若无更新的反馈, 该 issue 将于 **1 天**后关闭.

**Comment by Robin7Ma** [comment]
好的，已解决，确实是python的依赖未安装。
直接下载的zip重命名不可以用，需要解压后到代码根目录压缩。
试用了一下，跟之前理解的功能不一样，我需要的实际是时间戳和日期互相转换的功能，
依然感谢您的帮助。

**Comment by Zeroto521** [comment]
> 时间戳和日期互相转换的功能

该功能可以使用 [该commit](https://github.com/Zeroto521/Flow.Launcher.Plugin.Timestamp/tree/ef250a392a13038231f7d9a6af46f5801fce2e72), 但目前相关功能已不在维护.
