### ISSUE TITLE
Datestamp issue

### ISSUE THREAD

**Issue by jacobmercy** [Zeroto521/Flow.Launcher.Plugin.Timestamp#3]
Selecting "date" seems to add time on the end. For example:

2022-06-12T00:00:00

Would also be nice to have alternate options for formatting dates and times.

**Comment by Zeroto521** [comment]
https://github.com/Zeroto521/Flow.Launcher.Plugin.Timestamp/blob/9a2d291ad1dd95c95a444b7528f908bf477ea198/plugin/ui.py#L29

```diff
- result.append(self.genformat(f'{date} {nowt}', _l('Date & Time')))
+ result.append(self.genformat(f'{nowt} {date}', _l('Time & Date')))
```

You can simply change the source code like this.
